### ISSUE TITLE
AccountIsDisabled https://azure365fileshare.blob.core.windows.net/soapui/SoapUI-5.4.0-windows.zip

### ISSUE THREAD

**Issue by mhoult22** [AjeetChouksey/vsts-extensions#4]
We have been successfully using the extension for a while now, but there is now an error when running as a task:
_

> ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.

_

When I manually try the link https://azure365fileshare.blob.core.windows.net/soapui/SoapUI-5.4.0-windows.zip I get an error:

> <Error>
> <Code>AccountIsDisabled</Code>
> <Message>
> The specified account is disabled. RequestId:ac8f51fe-601e-0050-0571-eee749000000 Time:2021-01-19T14:43:36.2602569Z
> </Message>
> </Error>

Please could you help?  
Thanks,
Michael

**Comment by AjeetChouksey-zz** [comment]
Hi Michael,

Thanks for letting me know. I have reactivated the account and hope this will fix the issue.
Do let me know if you face the same issue.

Thanks,
Ajeet
________________________________

**Comment by mhoult22** [comment]
Thank you Ajeet for a really quick response.  It's working again now.

**Comment by AjeetChouksey-zz** [comment]
> Thank you Ajeet for a really quick response. It's working again now.

If you find this extension useful, it will great you write a review for it.

**Comment by mhoult22** [comment]
Thanks Ajeet, I’ve just left a review on https://marketplace.visualstudio.com/items?itemName=AjeetChouksey.soapui&ssr=false#review-details

**Comment by mhoult22** [comment]
Hi Ajeet,

I meant to ask you at the time, have you seen the other issue I’m having with the extension? Warning when using SoapUI ADO extension · Issue #3 · AjeetChouksey/vsts-extensions (github.com)<https://github.com/AjeetChouksey/vsts-extensions/issues/3>.  Is this something you might be able to look at please?


Thanks,
Michael

**Comment by seleniumtech** [comment]
Hi Ajeet,
I am using this extension and it is great. Just wanted to know if there will be any update in the near future? Support for 5.5 version or above

**Comment by rajnegi** [comment]
@AjeetChouksey-zz 
I am facing this 'AccountIsDisabled' issue again.
https://azure365fileshare.blob.core.windows.net/soapui/SoapUI-5.4.0-windows.zip

Can you please do the needful? Thanks
